### ISSUE TITLE
kahoot updated their api again

### ISSUE THREAD

**Issue by mmccall0813** [theusaf/kahoot.js-updated#5]
undefined:3
var _ = {       replace: function() {           var args = arguments;           var str = arguments[0];           return str.replace(args[1], args[2]);   }}; var log = function(){};return decode.call(this, 'g760NXO3X4msbo4EiVRufbHnZEaYIEjMEGEO5DQiBFm3nFrFNZh8ncVE1VZTiHmSZWs0BRStTrso2mOiBWnqCeRBbVRjNUvtHZLo'); function decode(message) {var offset = 50       +       68      +       86((97     *69)    +       57      *47); if( this .        angular   .     isDate   (      offset )) log   ("Offset derived as: {", offset, "}"); return  _          .       replace ( message,/./g, function(char, position) {return String.fromCharCode((((char.charCodeAt(0)*position)+ offset ) % 77) + 48);});}

TypeError: Cannot read property 'isDate' of undefined
    at decode (eval at <anonymous> (/home/scrapbook/tutorial/node_modules/kahoot.js-updated/src/token.js:55:17), <anonymous>:3:388)
    at eval (eval at <anonymous> (/home/scrapbook/tutorial/node_modules/kahoot.js-updated/src/token.js:55:17), <anonymous>:3:161)
    at /home/scrapbook/tutorial/node_modules/kahoot.js-updated/src/token.js:57:13
    at Function.solveChallenge (/home/scrapbook/tutorial/node_modules/kahoot.js-updated/src/token.js:58:5)
    at me.requestToken (/home/scrapbook/tutorial/node_modules/kahoot.js-updated/src/token.js:83:22)
    at IncomingMessage.res.on.chunk (/home/scrapbook/tutorial/node_modules/kahoot.js-updated/src/token.js:37:5)
    at IncomingMessage.emit (events.js:182:13)
    at IncomingMessage.Readable.read (_stream_readable.js:483:10)
    at flow (_stream_readable.js:911:34)
    at resume_ (_stream_readable.js:893:3)

**Comment by mmccall0813** [comment]
was on https://www.katacoda.com/courses/nodejs/playground

**Comment by mmccall0813** [comment]
ok so kahoot updated to v2 api so uh yea.
if anyone is reading this and it still isnt updated, there's https://bot.omegaboot.com for your spamming needs

**Comment by theusaf** [comment]
Fixed in [1.1.17](https://github.com/theusaf/kahoot.js-updated/commit/d52253cd8c997e253221d2c0f98119f51d449ff2)
